electron/cation

src/24-hour-rule.ts, src/constants.ts
As in title and as discussed in api-wg
=> feat: change 24 rule to 7 day rule for semver/minor and semver/major

.gitignore, package-lock.json, package.json, src/24-hour-rule.ts, src/enforce-semver-labels.ts, src/index.ts
=> feat: add semver/* label enforcement on all new PRs

package-lock.json, package.json, src/24-hour-rule.ts, src/api-review-state.ts, src/constants.ts, src/index.ts
Closes https://github.com/electron/cation/issues/24.
Also had to update Probot.
=> feat: auto-label semver/{minor, major} PRs

src/api-review-state.ts, src/constants.ts
=> feat: buttons

src/api-review-state.ts, src/constants.ts, src/enums.ts
=> feat: validate API decision sender

src/api-review-state.ts
Closes https://github.com/electron/cation/issues/33.
Tada
=> feat: make the buttons update the check run body

src/api-review-state.ts
Only allow the API WG chair to decline an API on behalf of the WG.
=> feat: only allow the API WG chair to decline an API

src/24-hour-rule.ts, src/api-review-state.ts
=> feat: update labels when new-pr is gone

src/24-hour-rule.ts, src/api-review-state.ts
=> feat: update API Review check when new-pr is removed

package-lock.json, package.json, src/24-hour-rule.ts, src/api-review-state.ts, src/enforce-semver-labels.ts
=> fix: clean up EventPayloads types

src/api-review-state.ts
The author of the PR should not be able to LGTM their own API.
=> fix: prevent pr author from LGTMing own PR

.github/workflows/lint.yml, package-lock.json, package.json
=> build: add lint workflow

src/24-hour-rule.ts
Closes https://github.com/electron/cation/issues/46.
The new-pr label was added but the semver label was missing - per [existing logic](https://github.com/electron/cation/blob/master/src/24-hour-rule.ts#L26-L27) we assume this means that it's semver-major and thus the open time should be a week. However, since the 24 hour rule does not currently listen to the `pull_request.labeled` event there is no way to tell it that it has a different semver label than initially assumed when one is applied. This is fixed by listening to the `pull_request.labeled` event and taking action if the label is a backport label, fast track label, semver label, or new-pr label.
=> fix: update new-pr label if semver changes

package-lock.json, package.json, src/index.ts
=> feat: add sentry error monitoring

README.md
=> docs: add README with basic overview

spec/24-hour-rule.spec.ts, src/24-hour-rule.ts, src/api-review-state.ts, src/utils/label-utils.ts
Make clearer what labels are being added/removed during cron check for logging and also don't try to add extant labels.
=> fix: don't try to add label which already exists

src/24-hour-rule.ts, src/api-review-state.ts, src/constants.ts
Closes https://github.com/electron/cation/issues/67.
=> fix: update API review labels after time expiration

src/api-review-state.ts, src/constants.ts
Closes https://github.com/electron/cation/issues/71.
cc @MarshallOfSound
=> fix: remove API labels if exclude labels added

src/api-review-state.ts
Fixes https://sentry.io/organizations/electronjs/issues/2796476096/?project=5552563&referrer=slack
=> fix: checkRun initialization location

.github/workflows/lint.yml, .github/workflows/test.yml
Handle switch from `master` -> `main`
=> chore: update CI for master->main switch

src/add-triage-labels.ts
Removed unused imported `labelExistsOnPR` method
=> chore: removed unused import

package-lock.json, package.json, src/api-review-state.ts
Adds debug comments to aid future debugging.
=> chore: add debugging commentary

src/api-review-state.ts
Closes https://github.com/electron/cation/issues/111.
=> fix: prevent incorrect API review clobbering

package-lock.json, package.json, spec/24-hour-rule.spec.ts, spec/add-triage-labels.spec.ts, spec/api-review-state.spec.ts, spec/enforce-semver-labels.spec.ts, src/24-hour-rule.ts, src/api-review-state.ts, src/index.ts, src/utils/check-utils.ts
=> chore: update deps

src/enforce-semver-labels.ts
Closes https://github.com/electron/cation/issues/123
my bad
=> fix: update semver on PR synchronize

spec/api-review-state.spec.ts, src/api-review-state.ts
Closes https://github.com/electron/cation/issues/133.
Cleans up types as well and adds a few new tests.
=> fix: change requests superseding API LGTM

README.md
=> docs: add status badge to README.md

src/add-triage-labels.ts
=> fix: detect existing semver labels

spec/api-review-state.spec.ts, src/api-review-state.ts
This call was using the wrong data shape, so fix that and refactor to more strongly type it.
=> fix: correct data shape for octokit.checks.update call

package-lock.json
=> chore: update semver deep deps to clear audit

package-lock.json, package.json, spec/api-review-state.spec.ts, src/24-hour-rule.ts, src/api-review-state.ts, src/deprecation-review-state.ts
Fixes cation not paginating all of the PR reviews in https://github.com/electron/electron/pull/44411
~~I'm not sure why `octokit.paginate` is having trouble with types as I'm doing the same as in zoilist's code~~ there was a type conflict which resolved after updating dependencies
https://github.com/electron/zoilist/blob/c3d2e49c58a8b2d5e8c84ec220ba3675a7cc29d8/src/remind.ts#L64-L68
=> fix: paginate PR reviews
