electron/cation

src/24-hour-rule/index.ts, src/constants.ts
Do not add the `'new-pr 🌱'` label to backports or to `build`/`ci` PRs.
cc @MarshallOfSound
=> feat: don't add new-pr label to backports or some prefixes

src/24-hour-rule/index.ts, src/constants.ts
Two fixes in this one:
1) Backports with the `feat` prefix should receive the `new-pr 🌱` label.
2) Cation now checks for the presence of `backport` somewhere in the PR title to mitigate the race condition with `trop` adding the `backport` label.
cc @MarshallOfSound
=> fix: feat backports should still be labeled

src/constants.ts
Same as trop, allow `electron-bot` and `fasttrack` to bypass this check
=> feat: support electron-bot / fasttrack

src/constants.ts
Don't force a 24-hour hold on `spec`-only changes.
cc @MarshallOfSound @nornagon
=> chore: don't apply new-pr label to spec prs

src/api-review-state.ts, src/constants.ts, src/utils/check-utils.ts
This PR creates a check when a new PR is opened for API review management. This will ultimately be handled like Archaeologist - the API Review check will always exist and be neutral if not needed. It also handles potential unlabeling actions:
We want to prevent tampering with `api-review/*` labels other than request labels - the bot should control the full review lifecycle. Therefore, if an `api-review/*` label is removed there is only one circumstance under which this should be allowed. The `api-review/requested` label is the only label that can be removed by humans, and only if the PR is `semver-patch`. If any other `api-review/*` label is removed, it must be put back.
=> feat: handle api-review unlabeling

src/api-review-state.ts, src/constants.ts, src/enums.ts, src/utils/env-util.ts, src/utils/log-util.ts
Humans can only add the 'api-review/requested 🗳' manually. If other `api-review/*` labels are added, remove them.
=> feat: remove api-review/* labels added by humans

src/constants.ts, src/enforce-semver-labels.ts
Added explicitly here instead of to the enum as other things probably shouldn't be using it, it's an exception case
=> feat: allow semver/none in the semver label enforcement check

src/24-hour-rule.ts, src/api-review-state.ts, src/utils/label-utils.ts
Fixes 404s seen in Sentry:
caused by trying to remove labels which don't exist on a a given PR.
=> fix: don't remove nonexistent labels

src/api-review-state.ts
Refs https://github.com/electron/electron/pull/27047.
Only PRs to master and which don't otherwise have an exclusion label should be labeled `api-review/requested`
=> fix: only label master PRs with API review requested

src/24-hour-rule.ts
Refs https://github.com/electron/electron/pull/27047.
This is now handled by `backport-requested/xyz`
=> fix: feat backports do not need to have new-pr

src/index.ts
=> chore: update deprecated WebhookError props

src/api-review-state.ts, src/constants.ts
Including the minimum PR open time remaining in the check itself.
=> feat: include time remaining in check

src/api-review-state.ts
What it says on the tin. Make it clearer when the `api-review-required` label is removed from a PR what that means for the check.
=> fix: update title when Check is reset

src/24-hour-rule.ts
Close https://github.com/electron/cation/issues/74.
Fixes an issue where the API Review labels check wouldn't be updated after the `new-pr 🌱` label was removed.
cc @jkleinsc
=> fix: update API Review labels when new-pr is gone

src/api-review-state.ts, src/constants.ts
=> fix: use default_branch instead of hard-coding master

package-lock.json, src/api-review-state.ts, src/utils/label-utils.ts
Fixes an issue where if a `semver-{major|minor}` label is added to a PR and then removed and replaced with `semver-patch`, cation wouldn't appropriately remove the `api-requested` label.
=> fix: if semver label is updated to patch remove requested label

spec/24-hour-rule.spec.ts, spec/fixtures/pr-open-time/pull_request.opened.json, spec/fixtures/pr-open-time/pull_request.semver-major.json, spec/fixtures/pr-open-time/pull_request.semver-minor.json, spec/fixtures/pr-open-time/pull_request.semver-missing.json, spec/fixtures/pr-open-time/pull_request.semver-none.json, spec/fixtures/pr-open-time/pull_request.semver-patch.json, spec/fixtures/pr-open-time/pull_request.should_label.json, spec/fixtures/pr-open-time/pull_request.should_not_label.json, src/24-hour-rule.ts
Closes https://github.com/electron/cation/issues/13.
Applies PR label based _either_ on date when PR was opened, if it was never a draft, or the date that the PR was most recently marked ready for review.
=> feat: take ready-for-review into account for open time

spec/fixtures/add-triage-labels/build_pr_opened.json, spec/fixtures/add-triage-labels/ci_pr_opened.json, spec/fixtures/add-triage-labels/docs_pr_opened.json, spec/fixtures/add-triage-labels/test_pr_opened.json, src/add-triage-labels.ts
Only apply triage labels to PRs targeting master.
Trop handles backport labeling.
=> fix: only add labels to default branch

src/api-review-state.ts
Fixes issue seen here: https://github.com/electron/electron/pull/33641
where a user who both commented and reviewed with `API LGTM` would show up twice.
=> fix: filter comment/review duplicates

src/api-review-state.ts
Fixes issue seen in https://github.com/electron/electron/pull/35438 and https://github.com/electron/electron/pull/34526, where reviewers who left API LGTM comments would not have those comments recognized as formal approvals.
We were incorrectly making the implicit assumption that people who were commenting were _not_ also reviewing. - the logic deduplicates but also potentially filtered out LGTM comments from people who had _also_ left a review with no comment body.
This fixes that by initially filtering out all reviews with no comment body.
=> fix: removing LGTM comments with reviews

src/constants.ts
I'm not super familiar with `cation`, but on face value this feels correct? Labeling `trop` created PRs seems unnecessary and causes [stuff like this](https://github.com/electron/electron/pull/33147) where you get labels which don't provide any benefit on a backport (documentation), and conflicting labels (`semver/none` vs `semver/patch`).
=> chore: add trop to excluded users

spec/24-hour-rule.spec.ts, src/24-hour-rule.ts
Closes https://github.com/electron/cation/issues/128.
=> fix: don't apply new-pr to merged PRs

.github/workflows/lint.yml, .github/workflows/test.yml
* Pins SHAs for actions
* Restricts permissions for actions
* Updates `actions/setup-node` to clear deprecation warnings
=> build: update GitHub actions workflows

src/api-review-state.ts
Pops out of #144 from @jkleinsc's suggestions.
=> chore: return early in addOrUpdateAPIReviewCheck for forks

src/api-review-state.ts
This reverts commit f3b42b17135222f2d5dd9ef13ad0062b7a0ba208.
I misunderstood the change being made in #146 and didn't see that the existing code returns `users`, so the change was actually a behavior change. It was not caught in tests unfortunately, see #149 which fixes up the tests so that they correctly detect this mistake.
=> revert: return early in addOrUpdateAPIReviewCheck for forks

spec/deprecation-review-state.spec.ts, spec/fixtures/deprecation-review-state/issue_comment.checklist_incomplete.json, src/deprecation-review-state.ts
Fixes a bug and fixes various test issues which came out of #149. So needs that PR to land first.
=> fix: properly detect completed deprecation checklist

assets/deprecation-checklist.md
I incorrectly labeled https://github.com/electron/electron/pull/39341 as `semver/minor` - let's add a checklist item to ensure any deprecation PRs with removals are labeled as major. The link will render nicely as a label over on `e/e`.
=> chore: add semver/major checklist item to deprecation review

src/deprecation-review-state.ts
Fixes a race condition which happened on https://github.com/electron/electron/pull/39696 when the label was added at the same time as the PR was created. While there is a check to see if the comment already exists, since each webhook for label added was being processed in parallel, they all added the comment. Only add the comment if the relevant label is what triggered the event.
=> fix: only comment on event for deprecation-review/requested label added

.github/workflows/lint.yml, .github/workflows/test.yml
Bumps versions so everything is off EOL Node.js versions and preempts deprecation warnings.
=> ci: update workflows

spec/api-review-state.spec.ts, src/api-review-state.ts
This PR: https://github.com/electron/electron/pull/42561 illustrates an odd edge case in our approve/request changes workflow. If you request changes on the PR, the API Review is blocked (even if you were requesting changes to implementation or other non-API parts of the PR). If you subsequently approve the PR, the API Review is still blocked because we don't consider PR approvals to be API approvals.
After some discussion within the API WG, the consensus is that submitting a "Request Changes" to a PR should not be implicitly treated as an API request for changes. Instead, we should add an additional comment match for `API CHANGES REQUESTED` and use that to denote that a reviewer has requested changes to the API.
This PR implements this proposal, by removing checks for `REQUEST_CHANGES` …
=> feat: replace PR "Request Changes" with a "API CHANGES REQUESTED" comment

README.md, spec/api-review-state.spec.ts, spec/fixtures/api-review-state/pull_request.api-skip-delay_label.json, src/api-review-state.ts, src/constants.ts
As we've discussed over the last couple weeks, we want a way to manually skip the default 7 day delay for API Review approval, for API changes that need to land more quickly to address emergent issues (e.g. browser or OS upgrades).
This PR updates Cation to look for a new `api-review/skip-delay ⏰` label, and skip the 7 day delay if present.
I'm happy to update the PR with a different label name if anyone has a better suggestion 😄
=> feat: add `api-review/skip-delay ⏰` label

jest.config.js
I was poking at the Jest CLI trying to get it to just run related tests when I change source files, but it was failing to find related tests.
According to [this](https://stackoverflow.com/a/70613739), the reason Jest can't find related tests is because the `src` folder isn't in the `roots` list in the Jest config.
This PR updates the `roots` config to include the `src` folder.
Before:
```
> yarn jest --findRelatedTests src/api-review-state.ts
yarn run v1.22.22
$ C:\Users\itsananderson\src\cation\node_modules\.bin\jest --findRelatedTests src/api-review-state.ts
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\Users\itsananderson\src\cation
47 files checked.
testMatch:  - 0 matches
testPathIgnorePatterns: spec\\utils.ts - 46 matches
testRegex: …
```
=> Add 'src' folder to Jest roots

src/24-hour-rule.ts, src/api-review-state.ts, src/enforce-semver-labels.ts, src/utils/log-util.ts
These were probably needed in the past to work around shortcomings in the types, but now it looks like the types are accurate and we don't need to use `any`.
=> chore: remove 'any' types

src/24-hour-rule.ts, src/api-review-state.ts, src/utils/env-util.ts, src/utils/log-util.ts
Most of the "conversion" here is simply deleting `@param` and `@returns` which are only types, since they're redundant to the TS types, sometimes wrong, and TSDoc doesn't include types for obvious reasons.
=> chore: convert JSDoc comments to TSDoc

spec/api-review-state.spec.ts, spec/fixtures/api-review-state/pull_request.converted_to_draft.json, spec/fixtures/api-review-state/pull_request.ready_for_review.json, src/api-review-state.ts
Closes https://github.com/electron/cation/issues/172.
Cation shouldn't request API review automatically on a PR that's still in draft status. It should update labels accordingly if a PR is opened in draft, or if an open PR is converted in/out of draft.
=> feat: account for draft status when handling API review

src/api-review-state.ts
Allow removing API related labels from draft PRs.
=> fix: allow unlabeling draft PRs

.husky/pre-commit, package-lock.json, package.json, src/api-review-state.ts
As in title. Switches `@octokit/webhooks-definitions` to `@octokit/webhooks-types` (pinned to a version which matches the one used by `@octokit/rest@^19.0.4`) as the former [is deprecated](https://www.npmjs.com/package/@octokit/webhooks-definitions).
=> build: update dev dependencies

src/api-review-state.ts
Evidently this label isn't being respected for API Review PRs, but the lack of logging makes it hard to determine why. This adds some logs to make it easier to debug the issue.
=> feat: add log messages for api-review/skip-delay label handling

assets/deprecation-checklist.md
The filename was changed in https://github.com/electron/electron/pull/46808.
=> chore: update deprecation helpers link
